kind: Cluster
name: broker
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 6443
    hostPort: 6443
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        advertise-address: 119.28.118.26
      certSANs:
      - 127.0.0.1
      - 132.232.31.102
      - ::1
      - localhost
      - 119.28.118.26
networking:
  podSubnet: "10.44.0.0/16"
  serviceSubnet: "10.45.0.0/16"
  disableDefaultCNI: true